# Use postgres/example user/password credentials
version: '3.1'

services:
#  bot:
#    build:
#      dockerfile: Dockerfile.dev
#    restart: always
#    env_file:
#      - .env.development
#    depends_on:
#      - db
#    volumes:
#      - .:/usr/src/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 6666:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
